namespace MapInfo.Wrapper.MapOperations
{
    public enum MapperInfoTypes
    {
        MAPPER_INFO_ZOOM = 1,
        MAPPER_INFO_SCALE = 2,
        MAPPER_INFO_CENTERX = 3,
        MAPPER_INFO_CENTERY = 4,
        MAPPER_INFO_MINX = 5,
        MAPPER_INFO_MINY = 6,
        MAPPER_INFO_MAXX = 7,
        MAPPER_INFO_MAXY = 8,
        MAPPER_INFO_LAYERS = 9,
        MAPPER_INFO_EDIT_LAYER = 10,
        MAPPER_INFO_XYUNITS = 11,
        MAPPER_INFO_DISTUNITS = 12,
        MAPPER_INFO_AREAUNITS = 13,
        MAPPER_INFO_SCROLLBARS = 14,
        MAPPER_INFO_DISPLAY = 15,
        MAPPER_INFO_NUM_THEMATIC = 16,
        MAPPER_INFO_COORDSYS_CLAUSE = 17,
        MAPPER_INFO_COORDSYS_NAME = 18,
        MAPPER_INFO_MOVE_DUPLICATE_NODES = 19,
        MAPPER_INFO_DIST_CALC_TYPE = 20,
        MAPPER_INFO_DISPLAY_DMS = 21,
        MAPPER_INFO_COORDSYS_CLAUSE_WITH_BOUNDS = 22,
        MAPPER_INFO_CLIP_TYPE = 23,
        MAPPER_INFO_CLIP_REGION = 24,
        MAPPER_INFO_REPROJECTION = 25,
        MAPPER_INFO_RESAMPLING = 26,
        MAPPER_INFO_MERGE_MAP = 27,
        MAPPER_INFO_ALL_LAYERS = 28,
        MAPPER_INFO_GROUPLAYERS = 29,
        MAPPER_INFO_NUM_ADORNMENTS = 200,
        MAPPER_INFO_ADORNMENT = 200
    }
}
